import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFile } from "node:fs/promises";
import postcss from "postcss";
import tailwindcss from "@tailwindcss/postcss";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// PostCSS plugin for TailwindCSS that inlines CSS as JS
const postcssPlugin = {
  name: "postcss",
  setup(build) {
    build.onLoad({ filter: /\.css$/ }, async (args) => {
      const raw = await readFile(args.path, "utf8");
      const result = await postcss([tailwindcss]).process(raw, {
        from: args.path,
      });

      // Inline CSS as JavaScript that injects styles into DOM
      const contents = `
        (function() {
          if (typeof document !== 'undefined') {
            const styleEl = document.createElement('style');
            styleEl.id = 'bases-custom-views-styles';
            styleEl.textContent = ${JSON.stringify(result.css)};

            // Remove old style if exists
            const oldStyle = document.getElementById('bases-custom-views-styles');
            if (oldStyle) {
              oldStyle.remove();
            }

            document.head.appendChild(styleEl);
          }
        })();
      `;

      return {
        contents,
        loader: "js",
      };
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  loader: {
    ".tsx": "tsx",
    ".ts": "ts",
  },
  plugins: [postcssPlugin],
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
